config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :categories
  resources :comments
  resources :images
  resources :tags

  root 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_and_belongs_to_many :categories

  validates :title, presence: true
  validates :body, length: {minimum: 2}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def create
    @category = Category.new params[:category]
    if @category.save
      redirect_to '/categories'
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    if @category.update params[:category]
      redirect_to '/categories'
    else
      render 'edit'
    end
  end

  def index
    @categories = Category.order 'name ASC'
  end

  def show
    @category = Category.find params[:id]
  end

  def destroy
    @category = Category.find params[:id]
    if @category.destroy
      redirect_to '/categories'
    else
      redirect_to :back
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def create
      @post = Post.create params[:post]
      if @post.errors.any?
        render 'new'
      else
        redirect_to '/posts'
      end
    end

    def new
      @post = Post.new
    end

    def index
      @posts = Post.order :created_at
    end

    def edit
      @post = Post.find params[:id]
    end

    def update
      @post = Post.find params[:id]
      @post.update params[:post]
      redirect_to "/posts"
    end

    def show
      @post = Post.find params[:id]
    end

    def destroy
      @post = Post.find params[:id]
      if @post.delete
        redirect_to posts_path
      else
        redirect_to :back
      end
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @posts = Post.order 'created_at ASC'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<% if @category.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@category.errors.count, "error") %> prohibited this Category from being saved:</h2>

    <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@category) do |f| %>
  <div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :name %>
  </div>

  <div class="actions">
  <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', category_path %>&nbsp &#9830 &nbsp
<%= link_to 'Show', "/categories/#{@category.id}"%>

app/views/categories/index.html.erb
<h1>Categories</h1>
<ul>
<% @categories.each do |category| %>
<li><%= link_to category.name, "/categories/#{category.id}"%></li>
<% end %>
</ul>
<br><br>
<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Back', posts_path %>&nbsp &#9830 &nbsp
<%= link_to 'Categories', categories_path %>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<ul>
  <% @category.posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
  <% end %>
</ul>
<br><br>
<%= link_to 'Edit', "/categories/#{@category.id}/edit" %>&nbsp; &#9830; &nbsp;<%= link_to 'Back', '/categories' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogtk</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%# render partial: 'shared/toolbar' %>
<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@post) do |f| %>
  <div class="field">
  <%= f.label :title %><br />
  <%= f.text_field :title %>
  </div>

  <div class="field">
  <%= f.label :body %><br />
  <%= f.text_area :body %>
  </div>

  <div class="actions">
  <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>&nbsp &#9830 &nbsp
<%= link_to 'Show', "/posts/#{@post.id}"%>

app/views/posts/index.html.erb
<h1>Posts</h1>
<ul>
<% @posts.each do |post| %>
  <li><%= link_to post.title, "/posts/#{post.id}"%></li>
  <br>
<% end %>
</ul>

<%= link_to 'New post' , new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>
<br><br>
<%= link_to 'Back', posts_path %>&nbsp &#9830 &nbsp
<%= link_to 'Posts', posts_path %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div class="">
  <%= @post.body %>
</div>
<br><br><br>

<ul>
<% @post.categories.each do |category| %>
<li><%= link_to category.name, "/categories/#{category.id}"%></li>
<% end %>
</ul>
<%= link_to 'Back', posts_path %>&nbsp; &#9830; &nbsp;
<%= link_to 'Edit', "/posts/#{@post.id}/edit"%>&nbsp; &#9830; &nbsp;
<%= link_to 'Delete', post_path(@post), method: :delete %>&nbsp; &#9830; &nbsp;
<%= link_to 'Categories', categories_path %>

app/views/welcome/index.html.erb
<h1>My Blog</h1>
<% @posts.each do |post| %>
  <h2><%= post.title %></h2>
  <p>
    (<%= post.categories.map(&:name).join ', ' %>)
  </p>
  <p>
    <%= post.body %>
  </p>
<% end %>